// ============================================================
// supabase/types.ts — Database schema types
// ============================================================
//
// Hand-typed (not generated by `supabase gen types`) so the
// codebase doesn't need a `supabase` CLI. Update this file when
// you add new tables to supabase/migrations/*.sql.
// ============================================================

export type GameMode = 'kanji-drop' | 'battle' | 'kanji-stack';

export interface LeaderboardScoreRow {
  id: string;
  user_id: string;
  username: string;
  game_mode: GameMode;
  score: number;
  wave: number;
  kills: number;
  max_combo: number;
  duration_sec: number | null;
  played_at: string;
  created_at: string;
}

export interface PlayerSaveRow {
  user_id: string;
  state: Record<string, unknown>;
  schema_version: number;
  updated_at: string;
}

export interface ProfileRow {
  id: string;
  username: string;
  level: number;
  xp: number;
  created_at: string;
  updated_at: string;
}

export interface Database {
  public: {
    Tables: {
      leaderboard_scores: {
        Row: LeaderboardScoreRow;
        Insert: Omit<LeaderboardScoreRow, 'id' | 'created_at'>;
        Update: Partial<LeaderboardScoreRow>;
      };
      player_saves: {
        Row: PlayerSaveRow;
        Insert: Omit<PlayerSaveRow, 'updated_at'>;
        Update: Partial<Omit<PlayerSaveRow, 'user_id'>>;
      };
      profiles: {
        Row: ProfileRow;
        Insert: Omit<ProfileRow, 'created_at' | 'updated_at'>;
        Update: Partial<Omit<ProfileRow, 'id'>>;
      };
    };
  };
}
